### ISSUE TITLE
mail issue

### ISSUE THREAD

**Issue by apoca** [BitWeb/zf2-error-reporting-module#3]
Often get this error and the most worrying is that production users have the error and not the error page, they advise me to do in this case.

Error:

stream_socket_client(): unable to connect to tcp://mail.mydomain.com:25 (Connection timed out)
ErrorException
Severity 2
#0 [internal function]: BitWeb\ErrorReporting\Service\ErrorService->addPhpError(2, 'stream_socket_c...', '/var/www/esolid...', 203, Array)
#1 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Protocol/AbstractProtocol.php(203): stream_socket_client('tcp://mail.esol...', 110, 'Connection time...', 30)
#2 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Protocol/Smtp.php(149): Zend\Mail\Protocol\AbstractProtocol->_connect('tcp://mail.esol...')
#3 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(340): Zend\Mail\Protocol\Smtp->connect()
#4 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(326): Zend\Mail\Transport\Smtp->connect()
#5 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(337): Zend\Mail\Transport\Smtp->lazyLoadConnection()
#6 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(204): Zend\Mail\Transport\Smtp->connect()
#7 /var/www/esolidar/vendor/bitweb/mail/src/BitWeb/Mail/Service/MailService.php(169): Zend\Mail\Transport\Smtp->send(Object(Zend\Mail\Message))
#8 /var/www/esolidar/vendor/bitweb/mail/src/BitWeb/Mail/Service/MailService.php(113): BitWeb\Mail\Service\MailService->send(Object(Zend\Mail\Message), Array)
#9 [internal function]: BitWeb\Mail\Service\MailService->BitWeb\Mail\Service\{closure}(Object(Zend\EventManager\Event))
#10 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Object(Closure), Object(Zend\EventManager\Event))
#11 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('bitweb.mailServ...', Object(Zend\EventManager\Event), NULL)
#12 /var/www/esolidar/vendor/bitweb/error-reporting/src/BitWeb/ErrorReporting/Service/ErrorService.php(246): Zend\EventManager\EventManager->trigger('bitweb.mailServ...', NULL, Array)
#13 /var/www/esolidar/vendor/bitweb/error-reporting/src/BitWeb/ErrorReporting/Service/ErrorService.php(104): BitWeb\ErrorReporting\Service\ErrorService->composeAndSendErrorMail()
#14 /var/www/esolidar/vendor/bitweb/zf2-error-reporting-module/src/BitWeb/ErrorReportingModule/Module.php(58): BitWeb\ErrorReporting\Service\ErrorService->endErrorHandling()
#15 [internal function]: BitWeb\ErrorReportingModule\Module->onFinishAfterPostDispatch(Object(Zend\Mvc\MvcEvent))
#16 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('finish', Object(Zend\Mvc\MvcEvent), Array)
#18 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(353): Zend\EventManager\EventManager->trigger('finish', Object(Zend\Mvc\MvcEvent))
#19 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(309): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#20 /var/www/esolidar/public/index.php(17): Zend\Mvc\Application->run()
#21 {main}
Uncaught exception 'Zend\Mail\Protocol\Exception\RuntimeException' with message 'Connection timed out' in /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Protocol/AbstractProtocol.php:209 Stack trace: #0 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Protocol/Smtp.php(149): Zend\Mail\Protocol\AbstractProtocol->_connect('tcp://mail.esol...') #1 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(340): Zend\Mail\Protocol\Smtp->connect() #2 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(326): Zend\Mail\Transport\Smtp->connect() #3 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(337): Zend\Mail\Transport\Smtp->lazyLoadConnection() #4 /var/www/esolidar/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Smtp.php(204): Zend\Mail\Transport\Smtp->connect() #5 /var/www/esolidar/vendor/bitweb/mail/src/BitWeb/Mail/Service/MailService.php(169)
ErrorException
Severity 1
#0 /var/www/esolidar/vendor/bitweb/error-reporting/src/BitWeb/ErrorReporting/Service/ErrorService.php(77): BitWeb\ErrorReporting\Service\ErrorService->addPhpError(1, 'Uncaught except...', '/var/www/esolid...', 209)
#1 [internal function]: BitWeb\ErrorReporting\Service\ErrorService->endErrorHandlingWithFatal()
#2 {main}

**Comment by rammrain** [comment]
Hi,

Probably the issue in your server's internet connection or the SMTP server's internet connection. A solution for this could be to add a try .. catch block to `\BitWeb\Mail\MailService::send()`. If you do it, please make a PR.

**Comment by apoca** [comment]
Can I send the complete error? Can you give me your email..

**Comment by rammrain** [comment]
Hi,

Please poste the complete log here: http://pastebin.com/
