### ISSUE TITLE
Invalid header value detected

### ISSUE THREAD

**Issue by apoca** [BitWeb/zf2-error-reporting-module#4]
With new stable version Zf2 2.4.2 something wrong:

Fatal error: Uncaught exception 'Zend\Mail\Header\Exception\InvalidArgumentException' with message 'Invalid header value detected' in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php:61 Stack trace: #0 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php(35): Zend\Mail\Header\GenericHeader::splitHeaderLine('Content-Type:mu...') #1 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(236): Zend\Mail\Header\GenericHeader::fromString('Content-Type:mu...') #2 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(195): Zend\Mail\Headers->addHeaderLine('Content-Type', 'multipart/alter...') #3 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendf in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php on line 61

**Comment by apoca** [comment]
This is related with the zf2015-04 security patch.

What is the value when call Zend\Mail\Header\GenericHeader::splitHeaderLine?

**Comment by apoca** [comment]
It's a bug in the developer module https://github.com/BitWeb/mail/blob/master/src/BitWeb/Mail/Service/MailService.php#L157

Can you update?

**Comment by rammrain** [comment]
Please do a PR for it. Thanks!

**Comment by apoca** [comment]
Sorry but I do not understand what is PR :/

**Comment by rammrain** [comment]
PR in GitHub stands for Pull Request.

**Comment by apoca** [comment]
LOL sorry...

**Comment by tobre6** [comment]
New release of bitweb/mail module has been done. See the difference: https://github.com/BitWeb/mail/pull/1

Please update your project, it should be fixed now.

**Comment by apoca** [comment]
Ok thanks! I will try tomorrow :)

**Comment by apoca** [comment]
solved!
